# PATHS 
# dr -> directory with videos to use for training and or analysis
# project_path -> dlc project working directory (where the project will be stored)
# cfg_path -> path to the configure yaml file
paths-windows: 
  dr: 'D:\Dropbox (UCL - SWC)\Dropbox (UCL - SWC)\Rotation_vte\raw_data\trials_clips'                  
  project_path: 'D:\Dropbox (UCL - SWC)\Dropbox (UCL - SWC)\Rotation_vte\DLC_nets\Nets'
  cfg_path: 'D:\Dropbox (UCL - SWC)\Dropbox (UCL - SWC)\Rotation_vte\DLC_nets\Nets\maze-Federico-2018-11-12\config.yaml'
paths-mac: 
  cfg_path: "/Users/federicoclaudi/Desktop/testgui-Federico-2018-11-12/config.yaml"
  dr: "/Users/federicoclaudi/Dropbox (UCL - SWC)/Rotation_vte/raw_data/video"
  project_path: 'Users/federicoclaudi/Desktop'

# DLC project NAME
experiment: 'maze'
experimenter: 'Federico'

# DLC select videos options
get_training_vids_th: 0.010  # prop of videos to use to generate the training set [roughly]
min_num_vids: 14              # min number of videos to be used
video_format: 'mp4'

# DLC behaviour
extract_frames_mode: 'uniform'    # 'uniform' vs 'kmeans'

