# PATHS 
# dr -> directory with videos to use for training and or analysis
# project_path -> dlc project working directory (where the project will be stored)
# cfg_path -> path to the configure yaml file
paths: {
  windows: {
    dr: 'D:\Dropbox (UCL - SWC)\Dropbox (UCL - SWC)\DAQ\upstairs_rig\video_clips\videos_for_FC',                  
    project_path: 'D:\Dropbox (UCL - SWC)\Dropbox (UCL - SWC)\Rotation_vte\DLC_nets\Nets',
    cfg_path: 'D:\Dropbox (UCL - SWC)\Dropbox (UCL - SWC)\Rotation_vte\DLC_nets\Nets\testgui-Federico-2018-11-12\config.yaml'
  },
  mac: {
    cfg_path: "/Users/federicoclaudi/Desktop/testgui-Federico-2018-11-12/config.yaml",
    dr: "/Users/federicoclaudi/Dropbox (UCL - SWC)/Rotation_vte/raw_data/video",
    project_path: 'Users/federicoclaudi/Desktop'
  }
}

# DLC project NAME
experiment: 'testgui',
experimenter: 'Federico',


get_training_vids_th: 0.02,  # prop of videos to use to generate the training set [roughly]
min_num_vids: 5,              # min number of videos to be used


# DLC behaviour
extract_frames_mode: 'uniform'    # 'uniform' vs 'kmeans'

