# PATHS 
# dr -> directory with videos to use for training and or analysis
# project_path -> dlc project working directory (where the project will be stored)
# cfg_path -> path to the configure yaml file
paths-windows: 
  dr: Z:\branco\Federico\raw_behaviour\maze\trials_clips
  project_path: D:\Dropbox (UCL - SWC)\Rotation_vte\DLC_nets\Nets
  cfg_path: D:\Dropbox (UCL - SWC)\Rotation_vte\DLC_nets\Nets\maze-overview-Federico-2019-01-03\config.yaml
paths-mac: 
  cfg_path: "/Users/federicoclaudi/Desktop/testgui-Federico-2018-11-12/config.yaml"
  dr: "/Users/federicoclaudi/Rotation_vte/raw_data/video"
  project_path: 'Users/federicoclaudi/Desktop'

# DLC project NAME
experiment: 'forceplate'
experimenter: 'Egzona'

# DLC select videos options
number_of_training_videos: 5   # prop of videos to use to generate the training set [roughly]
min_num_vids: 3                 # min number of videos to be used
video_format: 'mp4'

# DLC behaviour
extract_frames_mode: 'kmeans'    # 'uniform' vs 'kmeans'